FROM --platform=linux/arm64/v8 ghcr.io/kosmoedge/nmf-libraries:2136
ARG VERSION
ENV APP=${APP}
ENV SUPERVISOR=${SUPERVISOR}
ENV VERSION=${VERSION}

RUN apt-get update
RUN apt-get install -y netcat
WORKDIR /mof
RUN cd sdk/ && mvn clean install
COPY scripts/start_module.sh .
COPY scripts/entrypoint.sh .
EXPOSE 1024
ENTRYPOINT [ "./entrypoint.sh" ]
