FROM --platform=linux/arm64/v8 ghcr.io/kosmoedge/nmf-libraries:2136
ARG VERSION
ENV VERSION=${VERSION}
RUN apt-get update
RUN apt-get install -y v4l-utils
RUN apt-get install -y fswebcam
RUN cd sdk && mvn clean install
WORKDIR /mof/sdk/sdk-package/target/nmf-sdk-${VERSION}/home/nmf/nanosat-mo-supervisor-sim
CMD ["./nanosat-mo-supervisor-sim.sh"]
